-- MySQL Script generated by MySQL Workbench
-- 11/08/19 22:21:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_extreme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_extreme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_extreme` DEFAULT CHARACTER SET utf8 ;
USE `db_extreme` ;

-- -----------------------------------------------------
-- Table `db_extreme`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_extreme`.`perfil` (
  `idperfil` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_extreme`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_extreme`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomecompleto` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(10) NOT NULL,
  `datadenascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `idperfil` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_Perfil1_idx` (`idperfil` ASC),
  CONSTRAINT `fk_usuario_Perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `db_extreme`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_extreme`.`cadastrodocurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_extreme`.`cadastrodocurso` (
  `idcadastrocurso` INT(11) NOT NULL AUTO_INCREMENT,
  `datadainscricao` DATE NOT NULL,
  `mensagem` VARCHAR(300) NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcadastrocurso`),
  INDEX `fk_CadastroDoCurso_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_CadastroDoCurso_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_extreme`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_extreme`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_extreme`.`comentario` (
  `idcomentario` INT(11) NOT NULL,
  `mensagem` VARCHAR(300) NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  `datahora` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_Comentário_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_Comentário_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_extreme`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_extreme`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_extreme`.`post` (
  `idpost` INT(11) NOT NULL AUTO_INCREMENT,
  `mensagem` VARCHAR(300) NOT NULL,
  `preco` FLOAT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  `idcadastrocurso` INT(11) NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_Post_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_Post_CadastroDoCurso1_idx` (`idcadastrocurso` ASC),
  CONSTRAINT `fk_Post_CadastroDoCurso1`
    FOREIGN KEY (`idcadastrocurso`)
    REFERENCES `db_extreme`.`cadastrodocurso` (`idcadastrocurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `db_extreme`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
